name: blume
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  appinio_swiper: ^2.1.1
  cached_network_image: ^3.4.1
  cherry_toast: ^1.13.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.9.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get: ^4.7.2
  google_fonts: ^6.3.0
  http: ^1.6.0
  http_parser: ^4.1.2
  image_picker: ^1.2.1
  path: ^1.9.1
  path_provider: ^2.1.5
  pinput: ^5.0.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  video_compress: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
